#Regression

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('/content/datasets_4458_8204_winequality-red.csv')

In [3]:
data

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[1599 rows x 12 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [5]:
data.describe()

fixed acidity  volatile acidity  ...      alcohol      quality
count    1599.000000       1599.000000  ...  1599.000000  1599.000000
mean        8.319637          0.527821  ...    10.422983     5.636023
std         1.741096          0.179060  ...     1.065668     0.807569
min         4.600000          0.120000  ...     8.400000     3.000000
25%         7.100000          0.390000  ...     9.500000     5.000000
50%         7.900000          0.520000  ...    10.200000     6.000000
75%         9.200000          0.640000  ...    11.100000     6.000000
max        15.900000          1.580000  ...    14.900000     8.000000

[8 rows x 12 columns]

In [27]:
data['quality'].unique()

array([5, 6, 7, 4, 8, 3])

In [28]:
data.corr()['quality'].sort_values(ascending=False)

quality                 1.000000
alcohol                 0.476166
sulphates               0.251397
citric acid             0.226373
fixed acidity           0.124052
residual sugar          0.013732
free sulfur dioxide    -0.050656
pH                     -0.057731
chlorides              -0.128907
density                -0.174919
total sulfur dioxide   -0.185100
volatile acidity       -0.390558
Name: quality, dtype: float64

#Seperate Features and Target

In [8]:
x = data.iloc[: , :-1].values
y = data.iloc[: , -1].values

In [9]:
x

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [10]:
y

array([5, 5, 5, ..., 6, 5, 6])

#Splitting data into Train and Test sets

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [13]:
x_train

array([[ 9.1 ,  0.52,  0.33, ...,  3.24,  0.6 ,  9.3 ],
       [ 9.4 ,  0.24,  0.33, ...,  3.47,  0.9 , 10.2 ],
       [ 6.3 ,  0.57,  0.28, ...,  3.41,  0.6 , 12.8 ],
       ...,
       [10.5 ,  0.43,  0.35, ...,  3.21,  0.69, 10.5 ],
       [10.8 ,  0.45,  0.33, ...,  3.24,  0.71, 10.8 ],
       [ 6.8 ,  0.77,  0.  , ...,  3.62,  0.68,  9.9 ]])

In [31]:
y_train

array([5, 6, 5, ..., 6, 5, 5])

In [32]:
y_test

array([7, 5, 5, 6, 7, 6, 6, 6, 6, 7, 5, 5, 6, 6, 5, 5, 6, 6, 6, 6, 5, 5,
       5, 5, 5, 5, 5, 7, 7, 6, 5, 5, 5, 6, 5, 5, 6, 5, 6, 6, 4, 6, 4, 6,
       6, 6, 6, 5, 7, 6, 5, 6, 6, 7, 5, 5, 4, 6, 6, 8, 5, 5, 5, 6, 6, 5,
       6, 6, 7, 6, 5, 5, 6, 5, 7, 6, 5, 6, 4, 5, 6, 7, 7, 6, 6, 6, 7, 5,
       6, 5, 5, 5, 5, 6, 6, 5, 5, 7, 5, 5, 5, 5, 6, 7, 6, 6, 4, 7, 5, 5,
       6, 7, 5, 6, 7, 7, 5, 5, 7, 5, 5, 5, 5, 5, 5, 4, 5, 6, 5, 7, 5, 6,
       5, 5, 6, 5, 6, 7, 5, 5, 6, 5, 5, 6, 6, 5, 7, 6, 5, 5, 6, 5, 5, 7,
       5, 6, 5, 6, 8, 6, 5, 7, 6, 6, 6, 6, 5, 7, 5, 5, 5, 6, 5, 5, 5, 6,
       5, 5, 5, 4, 7, 5, 5, 5, 5, 5, 5, 6, 6, 6, 5, 5, 5, 5, 6, 6, 5, 6,
       5, 5, 7, 6, 5, 5, 6, 6, 5, 6, 7, 5, 7, 5, 6, 5, 5, 5, 6, 6, 7, 8,
       6, 6, 5, 5, 5, 5, 6, 5, 5, 6, 6, 6, 6, 5, 5, 6, 5, 6, 4, 5, 7, 4,
       5, 5, 5, 5, 6, 5, 5, 6, 5, 5, 6, 6, 5, 5, 4, 6, 5, 6, 5, 4, 5, 5,
       5, 6, 5, 5, 5, 7, 5, 6, 5, 6, 7, 6, 7, 6, 6, 7, 5, 5, 6, 6, 7, 7,
       5, 7, 6, 7, 7, 7, 5, 5, 5, 7, 6, 5, 5, 5, 6,

In [34]:
x_test

array([[11.1 ,  0.42,  0.47, ...,  3.24,  0.77, 12.1 ],
       [ 6.8 ,  0.69,  0.  , ...,  3.46,  0.72, 10.2 ],
       [ 6.2 ,  0.45,  0.2 , ...,  3.41,  0.56,  9.2 ],
       ...,
       [ 5.7 ,  1.13,  0.09, ...,  3.5 ,  0.48,  9.8 ],
       [ 6.  ,  0.58,  0.2 , ...,  3.58,  0.67, 12.5 ],
       [ 7.9 ,  0.34,  0.42, ...,  3.35,  0.6 , 11.4 ]])

#Standardisation

In [36]:
from sklearn.preprocessing import StandardScaler

In [37]:
ntrain = y_train.reshape(len(y_train), 1)
ntest = y_test.reshape(len(y_test), 1)

In [38]:
ntrain

array([[5],
       [6],
       [5],
       ...,
       [6],
       [5],
       [5]])

In [39]:
ntest

array([[7],
       [5],
       [5],
       [6],
       [7],
       [6],
       [6],
       [6],
       [6],
       [7],
       [5],
       [5],
       [6],
       [6],
       [5],
       [5],
       [6],
       [6],
       [6],
       [6],
       [5],
       [5],
       [5],
       [5],
       [5],
       [5],
       [5],
       [7],
       [7],
       [6],
       [5],
       [5],
       [5],
       [6],
       [5],
       [5],
       [6],
       [5],
       [6],
       [6],
       [4],
       [6],
       [4],
       [6],
       [6],
       [6],
       [6],
       [5],
       [7],
       [6],
       [5],
       [6],
       [6],
       [7],
       [5],
       [5],
       [4],
       [6],
       [6],
       [8],
       [5],
       [5],
       [5],
       [6],
       [6],
       [5],
       [6],
       [6],
       [7],
       [6],
       [5],
       [5],
       [6],
       [5],
       [7],
       [6],
       [5],
       [6],
       [4],
       [5],
       [6],
       [7],
       [7],
    

In [40]:
x_sc = StandardScaler()
y_sc = StandardScaler()

In [41]:
xn_train = x_sc.fit_transform(x_train)
yn_train = y_sc.fit_transform(ntrain)

In [42]:
xn_test = x_sc.transform(x_test)
yn_test = y_sc.transform(ntest)

In [43]:
len(xn_train)

1279

In [44]:
xn_train

array([[ 0.45532085, -0.03868136,  0.31016332, ..., -0.46775149,
        -0.34240418, -1.04134212],
       [ 0.63109971, -1.59602467,  0.31016332, ...,  1.046816  ,
         1.4332477 , -0.19242231],
       [-1.18528185,  0.23941566,  0.05293411, ...,  0.65171144,
        -0.34240418,  2.26001268],
       ...,
       [ 1.2756222 , -0.539256  ,  0.413055  , ..., -0.66530377,
         0.19029139,  0.09055095],
       [ 1.45140106, -0.42801719,  0.31016332, ..., -0.46775149,
         0.30866818,  0.37352422],
       [-0.89231708,  1.35180374, -1.38754944, ...,  2.0345774 ,
         0.13110299, -0.47539558]])

In [45]:
len(xn_test)

320

In [46]:
xn_test

array([[ 1.62717992, -0.5948754 ,  1.03040509, ..., -0.46775149,
         0.66379855,  1.59974172],
       [-0.89231708,  0.90684851, -1.38754944, ...,  0.98096524,
         0.36785657, -0.19242231],
       [-1.24387481, -0.42801719, -0.35863262, ...,  0.65171144,
        -0.57915776, -1.13566654],
       ...,
       [-1.53683957,  3.35410228, -0.92453687, ...,  1.24436828,
        -1.05266493, -0.56972001],
       [-1.36106071,  0.29503506, -0.35863262, ...,  1.77117436,
         0.0719146 ,  1.97703942],
       [-0.24779459, -1.03983063,  0.77317588, ...,  0.25660687,
        -0.34240418,  0.93947076]])

In [47]:
yn_train

array([[-0.79959407],
       [ 0.44757766],
       [-0.79959407],
       ...,
       [ 0.44757766],
       [-0.79959407],
       [-0.79959407]])

#Train on different alogorithms

In [14]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

In [48]:
m_reg = LinearRegression()
p_reg = LinearRegression()
d_reg = DecisionTreeRegressor()
r_reg = RandomForestRegressor(n_estimators=500)

In [16]:
x_poly = PolynomialFeatures(degree =2)
x_poly = x_poly.fit_transform(x_train)

In [18]:
m_reg.fit(x_train, y_train)
p_reg.fit(x_poly,y_train)
d_reg.fit(x_train, y_train)
r_reg.fit(x_train, y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=500, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [19]:
temp = PolynomialFeatures(degree =2)
temp = temp.fit_transform(x_test)

In [20]:
m_pred = m_reg.predict(x_test)
p_pred = p_reg.predict(temp)
d_pred = d_reg.predict(x_test)
r_pred = r_reg.predict(x_test)

In [25]:
from sklearn.metrics import r2_score

In [24]:
m = r2_score(y_test, m_pred)
p = r2_score(y_test, p_pred)
d = r2_score(y_test, d_pred)
r = r2_score(y_test, r_pred)

#Result

In [26]:
print('Logistic Regression: ' + str(m) + '\npolyfeat: ' + str(p) + '\nDecision Tree: ' + str(d) + '\nRandom Forest: ' + str(r))

Logistic Regression: 0.3697696933338003
polyfeat: 0.3469391045801342
Decision Tree: 0.03969506905036202
Random Forest: 0.5250689900584546


#conclusion
* Since Random forest is giving more efficiency than other algorithm, we can consider random forest as the best algorithm for this dataset